### ISSUE TITLE
CRITICAL: KeyError ‘JINJA_EXTENSIONS' 

### ISSUE THREAD

**Issue by Euruson** [limbenjamin/voce#1]
I installed this theme following the "README.md", but it doesn't work. When I use `pelican content` , `CRITICAL: KeyError: u'JINJA_EXTENSIONS'  ` happens.

My pyenv:
```
adium-theme-ubuntu (0.3.4)
blinker (1.4)
cssmin (0.2.0)
docutils (0.13.1)
enum34 (1.1.6)
feedgenerator (1.9)
Jinja2 (2.9.6)
libsass (0.7.0)
MarkupSafe (1.0)
pathlib (1.0.1)
pelican (3.7.1)
pip (9.0.1)
ply (3.4)
Pygments (2.2.0)
pyScss (1.3.4)
python-dateutil (2.6.0)
pytz (2017.2)
setuptools (20.7.0)
six (1.10.0)
slimit (0.8.1)
Unidecode (0.4.20)
unity-lens-photos (1.0)
webassets (0.11)
wheel (0.29.0)
```

**Comment by Euruson** [comment]
Well, the "assets" plugin in this repo  is too old for Pelican(3.7.1). Download [getpelican/pelican-plugins/assets](https://github.com/getpelican/pelican-plugins/tree/master/assets), and it can work.

**Comment by limbenjamin** [comment]
Thanks. Will add it to the README.
