### ISSUE TITLE
kj typo left in the article.html file in the theme

### ISSUE THREAD

**Issue by abdulwahidgul24085** [limbenjamin/voce#10]
Hi, you have a typo in the article page see the below attachment.
![Screen Shot 2020-04-03 at 2 35 38 PM](https://user-images.githubusercontent.com/6042059/78351841-855b3200-75b8-11ea-94c9-6bb705b2aebb.png)

**Comment by limbenjamin** [comment]
Fixed. Thanks for letting me know.
