### ISSUE TITLE
theme assumes that the sitename is .com

### ISSUE THREAD

**Issue by abdulwahidgul24085** [limbenjamin/voce#11]
Hi, Just to give you a little heads up which is unique to anyone using the theme with a none .com domain. The site name will be ending in .com. For e.g. my domain is [my domain](abdulwahidgul.me) but when you put the .com my site name
![Screen Shot 2020-04-03 at 6 58 16 PM](https://user-images.githubusercontent.com/6042059/78375188-7dfa4f80-75dd-11ea-99a8-657cf2f7bccb.png)
 which is in the title of the theme becomes abdulwahidgul.com or abdulwahidgul.me.com. This cause a lot of confusion for me. So would like to point that out too.

**Comment by limbenjamin** [comment]
Fixed. Closed
