### ISSUE TITLE
footnote in rst behave incorrectly

### ISSUE THREAD

**Issue by euri10** [limbenjamin/voce#2]
hello, I'm not sure it's the theme but, using this simple .rst file:

```
testing a footnote
===========================

:date: 2017-07-16 00:00
:modified: 2017-07-16 00:00
:slug: footnote
:authors: euri10

this is a footnote [#foot]_

.. [#foot] http://example.com
```
when I click on the footnote it redirects me to SITE_URL/#foot while using no theme it goes back and forth from the footnote anchor to the footer anchor as I would expect it.

you can see the "wrong" behaviour on http://blog.bartab.fr/garmin-on-linux-sucks.html for instance, clicking on a footnote doesn't go to the desired anchor

the html output with no theme is 
```
 <p>this is a footnote <a class="footnote-reference" href="#foot" id="id1">[1]</a></p>
<table class="docutils footnote" frame="void" id="foot" rules="none">
<colgroup><col class="label" /><col /></colgroup>
<tbody valign="top">
<tr><td class="label"><a class="fn-backref" href="#id1">[1]</a></td><td><a class="reference external" href="http://example.com">http://example.com</a></td></tr>
</tbody>
</table>
```
with the theme enabled I see no difference with the footnotes html output, so I'm at a loss as to why it behaves differently with no them and with your theme enabled.

Is it a misconfiguration on my end or something that the theme does that is incorrect ?

**Comment by limbenjamin** [comment]
Hi euri10, 

This problem is caused by line 10 of base.html. If this line is removed, the anchor text will work. However, it will break a lot of other pages since the pages use relative links. I will be pushing a fix shortly. Thanks for bringing it up.

`<base href="http://blog.bartab.fr">`

**Comment by limbenjamin** [comment]
I have made the change. Nothing broke. Just make sure the LINKS in pelicanconf.py has a leading slash.

```
LINKS = (('Home','/index.html'),
('About','/pages/about.html'),)
```
