### ISSUE TITLE
Syntax Highlighting not working

### ISSUE THREAD

**Issue by thanospmc** [limbenjamin/voce#4]
Hello, first of all thanks for the theme, it's quite nice!

But I cannot get the syntax highlighting to work. Any specific class that needs to be specified in the pelicanconf or am I missing something else?

The CSS class for highlighting in the style.css is div.highlight while the default for code hilite is the highlight class. Not sure if this is normal, but it does not seem to recognize it.

**Comment by limbenjamin** [comment]
My pelicanconf.py looks like this.

`MD_EXTENSIONS=['codehilite(css_class=highlight, guess_lang=False, linenums=True)', 'extra', 'admonition']`

In my markdown articles, this is how I indicate a code section

```
	:::ps1

	$hashTable = @{}
	ForEach ($time in $times){
		$indisteps = $($time.IndiSteps)
		$hashTable[$key] = $indisteps 
	}
```

**Comment by bksahu** [comment]
> My pelicanconf.py looks like this.
> 
> `MD_EXTENSIONS=['codehilite(css_class=highlight, guess_lang=False, linenums=True)', 'extra', 'admonition']`
> 
> In my markdown articles, this is how I indicate a code section
> 
> ```
> 	:::ps1
> 
> 	$hashTable = @{}
> 	ForEach ($time in $times){
> 		$indisteps = $($time.IndiSteps)
> 		$hashTable[$key] = $indisteps 
> 	}
> ```

@limbenjamin I tried it but it still doesn't work. Btw I am using pelican 4. Although I thing tends to work if I put it inside this `<div class="codehilite"><pre><code></code></pre></div>` tag. 

My pelicanconf.py looks like this
`'MARKDOWN': {'extension_configs': {'markdown.extensions.codehilite': {'css_class': 'highlight'},
                                    'markdown.extensions.extra': {},
                                    'markdown.extensions.meta': {}},
              'output_format': 'html5'},
`

**Comment by limbenjamin** [comment]
I have not tried out pelican 4.

You might want to try

`'MARKDOWN': {'extension_configs': {'markdown.extensions.codehilite': {'css_class': 'codehilite'}, 'markdown.extensions.extra': {}, 'markdown.extensions.meta': {}}, 'output_format': 'html5'},`
