### ISSUE TITLE
User logo not working

### ISSUE THREAD

**Issue by sarudego** [limbenjamin/voce#7]
Hello,
first of all thanks for the theme, it is awesome!.

I don't know how to configure the USER_LOGO_URL, i have try this config:

![image](https://user-images.githubusercontent.com/14003015/59469082-1dbed500-8e34-11e9-9017-d4c94453f609.png)

Favicon and another image inside a .rst file works with this config:
![image](https://user-images.githubusercontent.com/14003015/59469163-4e9f0a00-8e34-11e9-9048-9d48bfd27cf2.png)

What i am doing bad?

Thanks for your time!

**Comment by limbenjamin** [comment]
hi sarudego, 

Look for this line in the HTML code of your homepage. Is the image src, a correctly formed URL? If it is not, you might have to change it.
`<img width="310" src="{{ USER_LOGO_URL }}" class="attachment-full size-full" alt="logo">`

You might have to try either one
`USER_LOGO_URL = 'pictures/logo.jpg'`
`USER_LOGO_URL = 'http://yourwebsite.com/pictures/logo.jpg'`

Your favicon config is actually commented out. It works because favicon.ico is the default name.

**Comment by sarudego** [comment]
Hello limbenjamin!

Thanks for your quick response, but I still can not get it to work, I can change the favicon by entering the favicon path in STATIC_PATHS as seen in the image above.

On the other hand, USER_LOGO_URL I think it does not generate it well, since when doing pelican content && pelican --listen and inspect the page, the image tag appears with empty src, <img src = "" class = "attachment-full size -full "alt =" logo "width =" 310 ">

If I now modify that src = "" by src = "pictures / logo.jpg" it works perfectly. I tried to put the full url or another url of external images but it does not work either.

Thank you!

**Comment by limbenjamin** [comment]
Solved.

**Comment by sarudego** [comment]
Hi limbenjamin, not solved, I wanted to say that in localhost: 8000 when you inspect the page and manually modify the src of the image, it looks correct, but when you put the same url in pelicanconf.py, it is not generated when doing pelican content ...

I'm sorry I did not explain correctly, I still can not make it work with the pelican configuration.

Thanks.

**Comment by limbenjamin** [comment]
Can you run the command and paste the output here? 
`pelican -s /path/to/pelican/pelicanconf.py --print-settings`

You should have the following variable.
`'USER_LOGO_URL': u'pictures/logo.jpg',`

**Comment by sarudego** [comment]
Hi!

If i put USER_LOGO_URL with that format, when i make --print-settings i get this:
![image](https://user-images.githubusercontent.com/14003015/59680938-f6b92800-91d2-11e9-876f-cefcc95c69c3.png)

And if i make pelican content && pelican --listen i have this now:

![image](https://user-images.githubusercontent.com/14003015/59680877-cd000100-91d2-11e9-8d25-ab67bf10f61e.png)

![image](https://user-images.githubusercontent.com/14003015/59680886-d7ba9600-91d2-11e9-980e-8f7c57a7c049.png)

I don't understand nothing.

**Comment by limbenjamin** [comment]
If the environment variable are not showing up, then it is not a problem with the theme.

Something is wrong with your pelican installation, or you are not running it correctly. Please refer to the instructions to learn how to set up and publish a site.

https://docs.getpelican.com/en/stable/install.html
https://docs.getpelican.com/en/stable/publish.html
