### ISSUE TITLE
Problem when generate with publishconf

### ISSUE THREAD

**Issue by sarudego** [limbenjamin/voce#8]
Hello limbenjamin.

I have another problem that I have not found a solution for.

When I upload the repo to github pages or try to generate in local using publishconfig or with RELATIVE_URL = True / False instead of '', it seems that it does not render the theme, something like this appears:

![image](https://user-images.githubusercontent.com/14003015/59542364-b96c4600-8f05-11e9-989a-dd3b45e8143f.png)

And, when i try to go a tag page or another one, i get 404 always, using the conf explained above.

Thanks.

**Comment by limbenjamin** [comment]
Please try setting siteurl in publishconf.py

`SITEURL = 'http://localhost:8000'`

**Comment by limbenjamin** [comment]
As per #7 If the environment variable are not showing up, then it is not a problem with the theme.

Something is wrong with your pelican installation, or you are not running it correctly. Please refer to the instructions to learn how to set up and publish a site.

https://docs.getpelican.com/en/stable/install.html
https://docs.getpelican.com/en/stable/publish.html
